### NumPy Utilities


### np.where()

In [4]:
import numpy as np
arr = np.array([10, 3, 7, 2, 9])
result = np.where(arr>5,'High','Low')
print(result)


['High' 'Low' 'High' 'Low' 'High']


In [6]:
# Replace elements
arr = np.array([1,2,0,4,0,6])
result = np.where(arr == 0,'Zero','Non_Zero')
print(result)

['Non_Zero' 'Non_Zero' 'Zero' 'Non_Zero' 'Zero' 'Non_Zero']


### np.isnan()

In [10]:
arr = np.array([1, 2, np.nan, 4, np.nan])
print(np.isnan(arr))

[False False  True False  True]


In [13]:
#  Filter or count NaNs
arr = np.array([10, np.nan, 20, np.nan, 30,np.nan])
nan_count = np.isnan(arr).sum()
print(nan_count)

3


### np.isinf() – Check for Infinite Values 

In [17]:
import numpy as np
arr = np.array([1, 2, np.inf, -np.inf, 5])
print(np.isinf(arr))
arr[np.isinf(arr)] = 0
print(arr)


[False False  True  True False]
[1. 2. 0. 0. 5.]


In [25]:
# 🧠 Task:
# You are given an array of numerical values, some of which are infinite.
# Detect which elements are infinite.
# Replace all infinite values with -1.
# Print the cleaned array.
arr = np.array([1,2,np.inf,4,5,-np.inf])
print(np.isinf(arr))
arr[np.isinf(arr)] = -1
print(arr)

[False False  True False False  True]
[ 1.  2. -1.  4.  5. -1.]


In [28]:
# np.clip()
arr = np.array([1,5,10,25,60,32,43])
clipped_arr = np.clip(arr,5,20)
print("Original Array : ",arr)
print("Clipped Array : ",clipped_arr)

Original Array :  [ 1  5 10 25 60 32 43]
Clipped Array :  [ 5  5 10 20 20 20 20]


In [30]:
# Problesms
# You have temperature readings in °C from 7 days, but some sensors gave wrong values (too low or too high).
# Clip all values to be within a reasonable range: minimum = 10°C, maximum = 45°C.
temps = np.array([5, 12, 48, 30, 9, 50, 42])
clipped_temp = np.clip(temps,10,45)
print("Original Temp are : ",temps)
print("Adjusted Temp are : ",clipped_temp)

Original Temp are :  [ 5 12 48 30  9 50 42]
Adjusted Temp are :  [10 12 45 30 10 45 42]


In [32]:
arr = np.array([np.nan, 5, 50, -np.inf, 10, 100, np.inf])
# Step 1: Replace nan and inf with fixed value
arr[np.isnan(arr)] = 0
arr[np.isinf(arr)] = 999
print(arr)
# Step 2: Clip the values between 1 and 50


[  0.   5.  50. 999.  10. 100. 999.]
