### Reshape,Flatten



In [13]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print("Reshaping here : \n",a.reshape(1,6))
print("Flatting here : \n",a.flatten())
print("Transpose matrix is \n",a.T)


[[1 2 3]
 [4 5 6]]
Reshaping here : 
 [[1 2 3 4 5 6]]
Flatting here : 
 [1 2 3 4 5 6]
Transpose matrix is 
 [[1 4]
 [2 5]
 [3 6]]


In [24]:
# Flatten Array
b = np.array([[1,2,3],[4,70,7]])
print("Original array : \n",b)
c = b.flatten()
c[1] = 5000
print("Flatten array is : \n",c)
print("Original after flatten : \n",b)

Original array : 
 [[ 1  2  3]
 [ 4 70  7]]
Flatten array is : 
 [   1 5000    3    4   70    7]
Original after flatten : 
 [[ 1  2  3]
 [ 4 70  7]]


In [25]:
# Ravel Array
b = np.array([[1,2,3],[4,70,7]])
print("Original array : \n",b)
c = b.ravel()
c[1] = 5000
print("Ravel array is : \n",c)
print("Original after flatten : \n",b)

Original array : 
 [[ 1  2  3]
 [ 4 70  7]]
Ravel array is : 
 [   1 5000    3    4   70    7]
Original after flatten : 
 [[   1 5000    3]
 [   4   70    7]]


### Stacking Arrays (Vertical & Horizontal)

In [45]:
a = np.array([10,20,30])
b = np.array([70,80,90])
print(a)
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[10 20 30]
[10 20 30 70 80 90]
[[10 20 30]
 [70 80 90]]


### Splitting Arrays

In [64]:
# np.split()
a = np.array([10,20,30,40,50,60])
print("A array is \n",a)
print("A array After split : ",np.split(a,3))
b = np.array([[1,2,3,4],[4,70,7,50]])
print("B array is \n",b)
print("B array after split :",np.split(b,2))
# Horizontal split
resultH = np.hsplit(a,3)
print("Horizontla split is \n",resultH)
resultV = np.vsplit(b,2)
print("Vertical Split is \n",resultV)


A array is 
 [10 20 30 40 50 60]
A array After split :  [array([10, 20]), array([30, 40]), array([50, 60])]
B array is 
 [[ 1  2  3  4]
 [ 4 70  7 50]]
B array after split : [array([[1, 2, 3, 4]]), array([[ 4, 70,  7, 50]])]
Horizontla split is 
 [array([10, 20]), array([30, 40]), array([50, 60])]
Vertical Split is 
 [array([[1, 2, 3, 4]]), array([[ 4, 70,  7, 50]])]


### Practice Problems

In [66]:
#Reshape 1D array of 12 elements to 3x4.
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [67]:
# * Flatten a 2D array to 1D.
a = np.array([[1,2,3],[4,5,6]])
print(a.flatten())

[1 2 3 4 5 6]


In [70]:
# Transpose a 3x2 array.
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print("After Trasnpose : \n",a.T)

[[1 2]
 [3 4]
 [5 6]]
After Trasnpose : 
 [[1 3 5]
 [2 4 6]]


In [78]:
# * Horizontally stack two arrays.
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.hstack((a,b)))
c = np.array([[1,2,3,4],[4,70,7,50]])
d = np.array([[10,20,30,40],[40,70,70,50]])
print(np.hstack((c,d)))

[1 2 3 4 5 6]
[[ 1  2  3  4 10 20 30 40]
 [ 4 70  7 50 40 70 70 50]]


In [85]:
# * Split a 1D array of 6 elements into 3 equal parts.
a = np.array([1,2,3,4,5,6])
print(np.split(a,3))


[array([1, 2]), array([3, 4]), array([5, 6])]


In [84]:
import numpy as np  # First, make sure numpy is imported

# * Split a 1D array of 6 elements into 3 equal parts.
a = np.array([1,2,3,4,5,6])
# Use np.array_split() instead of a.split()
# np.array_split() is the correct function to split numpy arrays
print(np.array_split(a, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]
