### Add, Subtract, Multiply, Divide


In [3]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print("Sum is : ",a+b)
print("Difference is : ",a-b)
print("Product is : ",a*b)
print("Division is : ",a/b)

Sum is :  [ 6  8 10 12]
Difference is :  [-4 -4 -4 -4]
Product is :  [ 5 12 21 32]
Division is :  [0.2        0.33333333 0.42857143 0.5       ]


### Aggregate Functions

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Sum is :",np.sum(arr))
print("Mean is : ",np.mean(arr))
print("Median is : ",np.median(arr))
print("Max element is : ",np.max(arr))
print("Min element is : ",np.min(arr))


Sum is : 21
Mean is :  3.5
Median is :  3.5
Max element is :  6
Min element is :  1


### Axis-based Ops

In [53]:
arr = np.array([[1, 10, 3], [4, 5, 6]])
print(arr)
print("Sum across columns is : ",np.sum(arr,axis = 0))
print("Sum across rows is : ",np.sum(arr,axis=1))
print("Maximum element across column : ",np.max(arr,axis=0))
print("Maximum element across rows : ",np.max(arr,axis=1))

[[ 1 10  3]
 [ 4  5  6]]
Sum across columns is :  [ 5 15  9]
Sum across rows is :  [14 15]
Maximum element across column :  [ 4 10  6]
Maximum element across rows :  [10  6]


### Comparison Ops

In [23]:
arr = np.array([2, 4, 6, 8, 10])
print(arr>5)
print(arr==4)
print(arr != 8)
arr2d = np.array([[1, 3, 5], [7, 9, 11]])
print(arr2d > 5)

[False False  True  True  True]
[False  True False False False]
[ True  True  True False  True]
[[False False False]
 [ True  True  True]]


### Boolean Indexing

In [25]:
arr = np.array([2, 4, 6, 8, 10])
print(arr[arr > 5])  # [6 8 10]
print(arr>5)


[ 6  8 10]
[False False  True  True  True]


### Logical Ops


In [44]:
arr = np.array([4, 6, 8, 10, 12])
result_AND = np.logical_and(arr > 5,arr < 12)
print(result_AND)
print(arr[result_AND])
result_OR = np.logical_or(arr>5,arr<12)
print(result_OR)
print(arr[result_OR])
result_not = np.logical_not(arr>5)
print(result_not)
print(arr[result_not])

[False  True  True  True False]
[ 6  8 10]
[ True  True  True  True  True]
[ 4  6  8 10 12]
[ True False False False False]
[4]


### np.any() and np.all()

In [47]:
arr = np.array([2, 4, 6, 8])
print(np.all(arr > 5))
print(np.any(arr>5))

False
True


### Compare two arrays and return True where elements are equal

In [56]:
import numpy as np

# Two arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 0, 3, 7, 5])
print(a==b)
print(a[a==b])

[ True False  True False  True]
[1 3 5]
