In [1]:
import numpy as np

### Vectorized operations (+, -, *, /)

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
a+b

array([ 7,  9, 11, 13, 15])

In [4]:
a-b

array([-5, -5, -5, -5, -5])

In [5]:
a*b

array([ 6, 14, 24, 36, 50])

In [6]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

### Built-in functions : np.mean(), np.median(), np.std()

In [13]:
a = np.array([1,2,23,4,54,6,7])

In [14]:
print(np.mean(a))

13.857142857142858


In [15]:
print(np.median(a))

6.0


In [16]:
print(np.std(a))

17.75571192947354


### Challenge:1

###1
Find the average score
Find the median score, Find the standard deviation,Print a message:
If std deviation < 5 → "Scores are consistent"
Else → "Scores vary a lot"



In [21]:
scores = np.array([78, 82, 90, 88, 65, 70, 95, 80])
print("Avg score is : ",np.mean(scores))
print("Median score is ",np.median(scores))
print("Std deviation is ",np.std(scores))
if np.std(scores) > 5:
    print("Scores vary a lot")
else:
    print("Scores are consistent")

Avg score is :  81.0
Median score is  81.0
Std deviation is  9.447221813845593
Scores vary a lot


### 2
Use the same scores = np.array([78, 82, 90, 88, 65, 70, 95, 80]) from the last program and:
Print the min and max score, Print the index of the min and max value,
Print the total sum of scores

In [28]:
scores = np.array([78, 82, 90, 88, 65, 70, 95, 80])
print("Maximum socre is :",max(scores))
print("Minimum socre is :",min(scores))
print("Index of max score is : ",np.argmax(scores))
print("Index of min socre is :",np.argmin(scores))
print("Sum of all scores is :",np.sum(scores))



Maximum socre is : 95
Minimum socre is : 65
Index of max score is :  6
Index of min socre is : 4
Sum of all scores is : 648


### 3 Boolean Indexing in NumPy
marks = np.array([45, 67, 89, 34, 90, 56, 70, 23])
Print only the elements greater than 60, 
Print only the elements less than 50
Count how many students scored above 75
Print all values between 50 and 80



In [29]:
marks = np.array([45, 67, 89, 34, 90, 56, 70, 23]) 

In [37]:
# only the elements greater than 60
print("Marks > 60:", marks[marks > 60])
print("Marks <50: ",marks[marks < 50])
print("Count>75 :",np.sum(marks>75))
print("Marks between 50 and 80 :",marks[(marks >= 50) & (marks<=80) ])

Marks > 60: [67 89 90 70]
Marks <50:  [45 34 23]
Count>75 : 2
Marks between 50 and 80 : [67 56 70]


### Find square root of each element in array

In [44]:
marks = np.array([45, 67, 89, 34, 90, 56, 70, 23])
print(np.sqrt(marks))

[6.70820393 8.18535277 9.43398113 5.83095189 9.48683298 7.48331477
 8.36660027 4.79583152]


### Given 2D array, find sum of each column and each row

In [54]:
ex = np.array([[1,2,3],[4,5,6]])
print(ex)
print("Sum of each column is : ",np.sum(ex,axis = 0))
print("Sum of each row is : ",np.sum(ex,axis = 1))

[[1 2 3]
 [4 5 6]]
Sum of each column is :  [5 7 9]
Sum of each row is :  [ 6 15]
