### Advanced NumPy

In [8]:
import numpy as np
a = np.ones((2,3))
print(a)
b = np.full((3,2),3)
print(b)
np.matmul(a,b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

In [14]:
# Find the Determinant
c = np.identity(4)
np.linalg.det(c)


1.0

### Statistics


In [33]:
stats = np.array([[1,2,3],[4,5,6]])
stats



array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.min(stats,axis = 1)

array([1, 4])

In [26]:
np.max(stats,axis = 1)

array([3, 6])

In [34]:
np.sum(stats,axis = 0)

array([5, 7, 9])

In [35]:
np.sum(stats,axis = 1)

array([ 6, 15])

### Reorganizing Arrays

In [42]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape(8,1)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [47]:
# Vertically Stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
# Horizontal  Stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous

In [67]:
file = np.genfromtxt('data.txt',delimiter=',')
file = file.astype('int16')
file

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]], dtype=int16)

### Boolean Masking and Advanced Indexing


In [70]:
file > 15

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [74]:
file[file >= 15]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
      dtype=int16)

In [78]:
# You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,7]]

array([2, 3, 8])

In [86]:
np.any(file > 25,axis=1)

array([False, False,  True])

In [90]:
np.all(file >= 9,axis = 0)

array([False, False, False, False, False, False, False, False,  True,
        True])

In [92]:
((file>10) & (file <15))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [93]:
(~((file>10) & (file <15)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [121]:
# Broadcasting
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
a+b

array([[11, 22, 33],
       [14, 25, 36]])