### Miscellenous


In [2]:
#np.split(), np.array_split()

In [9]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([6,7,8,9,10])
print(np.split(a,3))
print(np.array_split(b,3))

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([6, 7]), array([8, 9]), array([10])]


In [19]:
### Sorting Arrays	np.sort(), np.argsort()
arr = np.array([52,30,56,75,1,51,6457])
sorted = np.sort(arr)
print(arr)
print(sorted)
print(arr)
indices = np.argsort(arr)
print(indices)
print(arr[indices])

[  52   30   56   75    1   51 6457]
[   1   30   51   52   56   75 6457]
[  52   30   56   75    1   51 6457]
[4 1 5 0 2 3 6]
[   1   30   51   52   56   75 6457]


In [23]:
# 2D Array Sorting (Row-wise or Column-wise)
arr2d = np.array([[3, 1, 10], [9, 7, 8]])
sorted_rows = np.sort(arr2d, axis=1)
print(arr2d)
print(sorted_rows)
sorted_columns = np.sort(arr2d,axis=0)
print(sorted_columns)


[[ 3  1 10]
 [ 9  7  8]]
[[ 1  3 10]
 [ 7  8  9]]
[[ 3  1  8]
 [ 9  7 10]]


In [33]:
# 5. Unique Element np.unique() with return_counts=True
a = np.array([1,2,3,4,4,3,2,1,4,3,2,3,7,1,7])
unique,counts = np.unique(a,return_counts = True)
print(unique)
print(counts)


[1 2 3 4 7]
[3 3 4 3 2]


### NumPy Math Ops + Matrix Math

In [35]:
# Element-wise Math Operations
# np.add(), np.subtract(), np.multiply(), np.divide()
# Power: np.power()  , Modulo: np.mod()

In [49]:
import numpy as np
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,2))
print(np.divide(a,2))
print(np.power(a,2))
print(np.mod(a,3))


[11 22 33]
[ 9 18 27]
[20 40 60]
[ 5. 10. 15.]
[100 400 900]
[1 2 0]


### Matrix Multiplication


In [56]:
# np.dot() or @ operator
A = np.array([1, 2,3, 4])
B = np.array([5, 6,7, 8])

print("Matrix Multiplication:\n", np.dot(A, B))
print(A @ B)


Matrix Multiplication:
 70
70


In [65]:
# np.matmul() – Matrix Multiplication
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
matmul = np.matmul(a,b)
print(matmul)
print(matmul.T)


[[19 22]
 [43 50]]
[[19 43]
 [22 50]]


In [81]:
# import numpy as np
A = np.array([[4, 7],
              [2, 6]])
A_inv = np.linalg.inv(A)
print("Original Matrix:\n", A)
print("Inverse Matrix:\n", A_inv)
# Verifying: A × A⁻¹ ≈ Identity
identity = np.dot(A, A_inv)
print("A * A_inv:\n", identity)

b = np.array([[4,7],[2,6]])
print("Array b is : \n",b)
b_inv = np.linalg.inv(b)
print("Inverted Array is :\n",b_inv)
identity = np.dot(b,b_inv)
print(identity)


Original Matrix:
 [[4 7]
 [2 6]]
Inverse Matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A * A_inv:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
Array b is : 
 [[4 7]
 [2 6]]
Inverted Array is :
 [[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
