### Indexing (1D & 2D)

In [3]:
# 1D exasmple
import numpy as np
a = np.array([1,2,3,4,5])
print(a[4])

5


In [6]:
# 2D example
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a[1,1])

[[1 2 3]
 [4 5 6]]
5


### Slicing

In [20]:
a = np.array([1,2,3,4,5])
print(a[0:2])
b = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(b)
print(b[0:3,2:5])


[1 2]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


### Boolean Indexing

In [24]:
a = np.array([1,2,3,4,5])
print(a[a<2])

[1]


### Update values using condition

In [27]:
a = np.array([1,2,3,4,5])
a[a<2] = 0
print(a)

[0 2 3 4 5]


### Iterating arrays

In [33]:
# Loop through array elements.
# 1D array
a = np.array([1,2,3,4,5])
for i in a:
    print(i,end=' ')

1 2 3 4 5 

In [45]:
# Loop through array elements.
# 2D array
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a.shape[0])
print(a.shape[1])
for i in range(a.shape[0]):
    for j in range(b.shape[1]):
        print(a[i][j],end = ' ')
    print()
    

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
5
1 2 3 4 5 
6 7 8 9 10 


# Practice Problems


In [63]:
# 1
#. Create a 2D array and:
#    * Print the first row
#   * Print the second column
#  * Print all elements > 5
a = np.array([[1,2,3],[4,5,6]])
print(a)
print("First Row is : ",a[0,:])
print("First column is : ",a[:,0])
print("All Second Column is :",a[:,2])
print("All Elements >5 :",a[a>5])

[[1 2 3]
 [4 5 6]]
First Row is :  [1 2 3]
First column is :  [1 4]
All Second Column is : [3 6]
All Elements >5 : [6]


In [64]:
# 2
# 2. Replace all odd numbers in an array with -1
a = np.array([1,2,3,4,5])
a[a % 2 != 0] = -1
print(a)

[-1  2 -1  4 -1]


In [67]:
# 3. 
# c3. Create a 3x3 matrix and print its diagonal
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.diag(a))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [71]:
# Iterate over a 2D array and print each element with 
# its position  (row, col)
a = np.array([[1,2,3],[4,5,6]])
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j], " ", i,j)

1   0 0
2   0 1
3   0 2
4   1 0
5   1 1
6   1 2


In [85]:
# 5. Create a 1D array of 10 elements. Slice:
# * First 5 elements
#   * Last 3 elements
#   * Every 2nd element
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[:5])
print(a[-3:])
print(a[::2])

[1 2 3 4 5]
[ 8  9 10]
[1 3 5 7 9]
