### Random Module

In [18]:
import numpy as np
print(np.random.rand())
print(np.random.rand(5))
b = np.random.rand(4,3)
print("Before round up :\n",+b)
print("After round up :\n",np.round(b,3))

0.21555526867516783
[0.84679737 0.56048156 0.89734437 0.08774993 0.15531224]
Before round up :
 [[0.14323903 0.48655965 0.75868291]
 [0.47409954 0.4231796  0.41099976]
 [0.12607339 0.45102989 0.08941269]
 [0.32269448 0.38548128 0.19483243]]
After round up :
 [[0.143 0.487 0.759]
 [0.474 0.423 0.411]
 [0.126 0.451 0.089]
 [0.323 0.385 0.195]]


In [38]:
# np.random.randint() 
print(np.random.randint(2,20,5))
# Create a 1D array of 5 random integers from 1 to 10
print(np.random.randint(1,10,5))
# Create a 3x3 matrix of random integers between 10 and 99
a = np.random.randint(10,99,(3,3))
print(a)
# Count how many values are even in the above matrix
print("Even values are :\n",np.sum(a % 2 ==0))


[13 13  6 13 19]
[8 3 9 7 9]
[[34 10 34]
 [78 48 26]
 [50 92 15]]
Even values are :
 8


In [49]:
# np.random.randn() 
arr = np.random.randn(5)
print("Random Normal Values:", arr)
matrix = np.random.randn(3, 3)
print("Normal Distribution Matrix:\n", matrix)
print("Mean:", np.mean(matrix))
print("Std Dev:", np.std(matrix))
print(np.random.randn(5))




Random Normal Values: [-0.43702367 -0.66701122  0.45537014  0.88263792 -0.93531768]
Normal Distribution Matrix:
 [[-0.62530927 -0.20532691 -0.5898923 ]
 [ 1.85699122  0.27266287 -0.13834936]
 [ 0.20648096  0.85480886 -0.5179556 ]]
Mean: 0.12379005082678679
Std Dev: 0.7620688582749375
[-0.44589951  1.02663456  0.7416615  -1.38745687  1.93574051]


In [76]:
# np.random.choice()
# Pick one random value from a list:
np.random.choice([10,20,30])
# Pick 3 random values with repetition:
np.random.choice([10,20,30,40,50],size = 3,replace = True)
# Pick 3 random values without repetition:
np.random.choice([1, 2, 3, 4, 5], size=3, replace=False)
# With custom probability:
np.random.choice([10, 20, 30,40,50], size=5, p=[0.1, 0.4, 0.4,0.05,0.05])


array([30, 30, 20, 30, 30])

In [88]:
# Create a list of 6 numbers and use np.random.choice() to select:
# One random number. Three numbers with repetition.
# Three numbers without repetition. Three numbers with custom probabilities.
array = [11,12,13,14,15,16,17]
print(np.random.choice(array))
print(np.random.choice(array,size = 3,replace = False))
print(np.random.choice(array,size = 4,replace = True))
print(np.random.choice(array,size = 4,replace = False,p= [0.1,0.4,0.4,0.1,0,0,0]))



16
[15 14 13]
[16 11 11 13]
[14 13 12 11]


In [92]:
# Seeding array
import numpy as np
np.random.seed(42)
# Set the seed (any integer works)
random_array1 = np.random.randint(1, 100, size=5)
print("First random array:", random_array1)
# Reset seed to same value
np.random.seed(42)
random_array2 = np.random.randint(1, 100, size=5)
print("Second random array:", random_array2)


First random array: [21 83 87 75 75]
Second random array: [52 93 15 72 61]


In [99]:
# Shuffle array
# import numpy as np
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)
print(b)

[2 4 3 5 1]
None


In [102]:
# Reference (View)
a = np.array([10,20,30,40,50])
b = a
b[0] = 100
print(a)

[100  20  30  40  50]


In [106]:
# Copy
a = np.array([10, 20, 30])
b = a.copy()   # This is a true copy
b[0] = 99
print("a:", a)  # Output: [10, 20, 30] – no change!


a: [10 20 30]
[2 3 4 6]
