In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Numpy Array:", arr)
print("Array Type:", type(arr))
print("Shape:", arr.shape)

Numpy Array: [1 2 3 4 5]
Array Type: <class 'numpy.ndarray'>
Shape: (5,)


In [8]:
import numpy as np
a = np.array([1,2,3],dtype='int16')
print(a)
a


[1 2 3]


array([1, 2, 3], dtype=int16)

In [7]:
b = np.array([[1,2.0,34.0],[5.5,6.0,14]])
print(b)

[[ 1.   2.  34. ]
 [ 5.5  6.  14. ]]


In [25]:
# Get Dimnension
b.ndim
a.ndim


1

In [27]:
#Get shape
a.shape 
#  (3,)
b.shape
# (2, 3)

(2, 3)

In [32]:
# data type
a.dtype
# dtype('int16')

dtype('int16')

In [34]:
# Data Type
b.dtype
#dtype('float64')

dtype('float64')

In [43]:
# Size
a.itemsize


2

In [44]:
a.nbytes


6

In [69]:
# Accessing/Changine Specific element
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
arr
# Get A specify Element
arr[1,5]  # 13
# Get a specific row
arr[0,:]  # array([1, 2, 3, 4, 5, 6, 7])
# Get a specific column
arr[:,-3]  # array([ 5, 12])
# Getting little more fancy
arr[0,1:6:2]   # array([2, 4, 6])
# Getting indexed element
arr[1,5] = 13
print(arr)  # [[ 1  2  3  4  5  6  7] [ 8  9 10 11 12 13 14]]
arr[:,2] = 5
print(arr)  # [[ 1  2  5  4  5  6  7] [ 8  9  5 11 12 13 14]]


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


In [12]:
# All Zero's metrics,Ones,Random Integer,Decimal number
import numpy as np
np.zeros((3,3,3))
np.ones((2,3,3),dtype='int16')
np.full((2,2),100)
np.full_like(b,4)
np.random.rand(2,4)
np.random.random_sample(b.shape)
np.random.randint(0,19,3)
np.random.randint(12,15,size=(2,3))
#Idenntity matrix
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# Repeating array
arr = np.array([[1,2,3]])
r = np.repeat(arr,3,axis =0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:-1,1:-1] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays !!!


In [40]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


### Mathematics

In [52]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [43]:
a + 2

array([3, 4, 5, 6])

In [44]:
a - 2

array([-1,  0,  1,  2])

In [45]:
a * 2

array([2, 4, 6, 8])

In [46]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [47]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [49]:
a ** 3

array([ 1,  8, 27, 64])

In [55]:
np.sin(b)

array([0.84147098, 0.        , 0.84147098, 0.        ])

### Practice problems

In [75]:
# 1.Create a 1D NumPy array from a list of 5 numbers.
import numpy as np
numbers = [10,20,30,40,50]
arr = np.array(numbers)
print("Numpy Array is",arr)
print("Size is : ",arr.size)
print("Shape is : ",arr.shape)
print("Type is : ",type(arr))

Numpy Array is [10 20 30 40 50]
Size is :  5
Shape is :  (5,)
Type is :  <class 'numpy.ndarray'>


In [77]:
# 2.Create a 2D array using np.array().
a = np.array([[1,2],[3,4]])
print(a)



[[1 2]
 [3 4]]


In [82]:
# 3. Find shape, size, and datatype of any array.
b = np.array([[1,2,3],[4,5,6]],dtype='int16')
print(b)
print("Shape is : ",b.shape)
print("Size is : ",b.size)
print("Data Type is :",b.dtype)

[[1 2 3]
 [4 5 6]]
Shape is :  (2, 3)
Size is :  6
Data Type is : int16


In [86]:
# 4. Slice and print first 3 elements of an array.
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0:3])

[1 2 3]


In [106]:
# 5. Use np.zeros((2,3)), np.ones((3,3)), np.eye(3), np.arange(10,20).
a = np.array([1,2,3,4,5])
b = np.zeros((2,3))
print(b)
c = np.ones((2,2))
print(c)
d = np.eye(4)
print(d)
e = np.arange(10,50)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [115]:
# 6. Reshape a 1D array of 12 elements into a 3x4 matrix.
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape(3,4)
print("Reshaped array is :\n",b)



Reshaped array is :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
